[package]
name = "algorithm"
version = "0.1.0"
authors = ["Samuel Catania <samueljcatania@gmail.com>"]
description = "The backbone algorithm for the Video Library of Babel"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"